config/routes.rb
Rails.application.routes.draw do
  resources :restaurants do
    resources :reviews, only: [:create]
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, :address, :category, presence: true
  validates :category, inclusion: { in: %w(chinese italian japanese french belgian),
    message: "%{value} is not a valid category" }
    # A restaurant’s category must belong to this fixed list: ["chinese", "italian", "japanese", "french", "belgian"].
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, inclusion: { in: 1..5,
    message: "%{value} is not a valid rating" }
    # A review must have a content.
    # A review must have a rating.
    # A review’s rating must be a number between 0 and 5.
    # A review’s rating must be an integer. For example, a review with a rating of 2.5 should be invalid!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @review = Review.new
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    redirect_to restaurant_path(@restaurant)
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to restaurants_path, status: :see_other
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save!
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <div class="container">
     <div class="navbar navbar-default navbar-header">
        <%= link_to 'Restaurants', "/restaurants" %>
        <%= link_to 'New', "/restaurants/new" %>
      </div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/restaurants/edit.html.erb
<div class="container">
  <h1>Edit restaurant</h1>
  <%= simple_form_for(@restaurant) do |f| %>
    <%= f.input :name %>
    <%= f.input :category %>
    <%= f.input :address %>
    <%= f.input :phone_number %>
    <%= f.submit %>
  <% end %>
</div>

app/views/restaurants/index.html.erb
<div class="container">
  <h1>Restaurants</h1>
  <ul>
  <%@restaurants.each do |restaurant| %>
    <h3>
    <%= link_to "#{restaurant.name}", "/restaurants/#{restaurant.id}" %>
    </h3>
    <p><%= restaurant.category  %></p>
    <p><%= restaurant.address  %></p>
    <p><%= restaurant.phone_number  %></p>
  <% end %>
  </ul>
</div>

app/views/restaurants/new.html.erb
<div class="container">
  <h1>New restaurant</h1>
  <%= simple_form_for(@restaurant) do |f| %>
    <%= f.input :name %>
    <%= f.input :category %>
    <%= f.input :address %>
    <%= f.input :phone_number %>
    <%= f.submit %>
  <% end %>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <h1><%= @restaurant.name %></h1>
  <p><%= @restaurant.category %></p>
  <p><%= @restaurant.address %></p>
  <p><%= @restaurant.phone_number %></p>
  <%= link_to "Edit", edit_restaurant_path(@restaurant),
  data: {turbo_method: :edit} %>
  <%= link_to "Delete",
  restaurant_path(@restaurant),
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
  <h2>Restaraunt Reviews</h2>
  <hr>
  <% @restaurant.reviews.each do |review| %>
    <p><%= review.rating %></p>
    <p><%= review.content %></p>
    <hr>
  <% end %>
  <h1>New Review</h1>
  <%= simple_form_for [@restaurant, @review] do |f| %>
      <%= f.input :rating %>
      <%= f.input :content %>
      <%= f.submit "Submit Review" %>
  <% end %>
</div>